{{- if .Values.podDisruptionBudget.enabled }}
{{- if .Values.frontend.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-frontend
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
{{- end }}
{{- if .Values.backend.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-backend
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
{{- end }}
{{- end }}
