{{- if .Values.podDisruptionBudget.enabled }}
{{- range $key, $app := .Values.apps }}
{{- if and $app.enabled ($app.podDisruptionBudget.enabled | default false) }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-{{ $key }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $key }}
spec:
  minAvailable: {{ $app.podDisruptionBudget.minAvailable | default 1 }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $key }}
{{- end }}
{{- end }}
{{- end }}
