{{- if .Values.monitoring.podMonitoring.enabled }}
{{- range $key, $app := .Values.apps }}
{{- if and $app.enabled ($app.monitoring.podMonitoring | default false) }}
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: {{ $key }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $key }}
spec:
  selector:
    matchLabels:
      {{- include "app.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $key }}
  endpoints:
    - port: http
      path: {{ $app.monitoring.path | default "/metrics" }}
      interval: {{ $.Values.monitoring.podMonitoring.interval }}
{{- end }}
{{- end }}
{{- end }}
